variables:
  PRIMARY_BRANCH: "main"
  DEPLOY_REPO: 'git@gitlab.clarium.tech:clarium-edge/clarium-edge-apps-deploy.git'
  TARGET_BRANCH: "stage-dev"
  MODULE: "employee-management-system"
  SOURCE_DIRECTORY: "./dist"
  TARGET_DIRECTORY: "emsui"

include:
  - project: "devops/gitlab_yamls"
    ref: "Framework_template"
    file: "react.gitlab-ci.yml"
